### ISSUE TITLE
Improve performance of CSS Processor

### ISSUE THREAD

**Issue by mdedetrich** [untyped/sbt-plugins#47]
The performance of the sbt-untyped LESS processor seems to take quite a bit of time for non trivial cases. I believe this may be due to the fact that it manually does dependency management on its own instead of using LESS's own dependancy management

This can probably be when we upgrade to LESS 1.5.x

**Comment by davegurnell** [comment]
Closing this as it's extremely old and there's no immediately obvious workaround.
