### ISSUE TITLE
Using compass with sbt-sass

### ISSUE THREAD

**Issue by alcarvalho** [untyped/sbt-plugins#65]
I have not found a way to use compass with this plugin. Looking at Plugin source code I haven't found a way to provide any options to the sass compiler. What I would like to do is to pass in the "--compass" parameter and maybe that would work.

Or am I missing something?

**Comment by davegurnell** [comment]
Closing this issue as it's extremely old.

Technically the custom tasks in the SASS plugin are written in the new macro task syntax now. Please feel free to take another look and submit a PR if you get it working.
