### ISSUE TITLE
Problem resolving sbt-js plugin

### ISSUE THREAD

**Issue by ivorwilliams** [untyped/sbt-plugins#72]
I've followed the initial steps in `README.md`, selecting version `0.8`, but am unable to download the plugin.  Here's the relevant `sbt` output, with references to other repos removed:

```
 92 [warn]  [FAILED     ] com.untyped#sbt-js;0.8!sbt-js.jar:  (0ms)
...
 99 [warn] ==== jcenter: tried
100 [warn]   https://jcenter.bintray.com/com/untyped/sbt-js_2.10_0.13/0.8/sbt-js-0.8.jar
101 [warn] ==== public: tried
102 [warn]   https://repo1.maven.org/maven2/com/untyped/sbt-js_2.10_0.13/0.8/sbt-js-0.8.jar
103 [warn] ==== Untyped Bintray: tried
104 [warn]   https://dl.bintray.com/untyped/maven/com/untyped/sbt-js_2.10_0.13/0.8/sbt-js-0.8.jar
...
```

This failure isn't surprising: I see the jar in the documented repository, but without Scala and sbt version numbers: https://dl.bintray.com/untyped/maven/com/untyped/sbt-js/0.8/sbt-js-0.8.jar

Has the plugin been published incorrectly, or do I need to take some other sbt configuration steps?

FWIW, I'm running sbt-version `0.13.9` and Scala version `2.11.7`.

**Comment by davegurnell** [comment]
Thanks for the heads up. I'll check it out when I get to the office in an
hour.

**Comment by ivorwilliams** [comment]
Thanks, @davegurnell.  FYI, I checked out `master` of the project (which appears to be `0.8` although it isn't tagged as such).  Running `sbt publishLocal` gave me the correctly named artifacts, and I was able to carry on with my investigation of `sbt-js`.  This is OK for a short term workaround, but it would be great to fix the real repo.

**Comment by davegurnell** [comment]
@ivorwilliams I've taken a look and I've got no idea what's going on. The same Bintray settings produce the correct results on the rest of my projects. No idea why this should be different.

I unfortunately don't have any more time to look at this right now. I'll have to come back to it during/after NEScala next week.

**Comment by davegurnell** [comment]
Also I've tagged master as 0.8. This is automated now but wasn't last release. Thanks for the spot!

**Comment by davegurnell** [comment]
One further note. I presume the problem is to do with my configuration of bintray-sbt (which I added for version 0.8). I've logged an issue over there to find out what I'm doing wrong:

https://github.com/softprops/bintray-sbt/issues/81

**Comment by luismfonseca** [comment]
This situation kinda sucks at the moment. That is, the old repository no longer works and the users of this plugin are left with no real alternatives other than publishing this artifact to their private repositories.

Perhaps, when you have more time, you could publish this to the Sonatype nexus? I don't really see why other similiar projects should stop you from doing so. As a user I'd very much like to have a reliable repository such as Sonatype.

**Comment by davegurnell** [comment]
Thanks for your message Luis. I appreciate it's a problem. I thought everything was running smoothly! I'll take a look as soon as I can.

If I don't hear from the bintray-sbt maintainers I will try to get the old repo back online. I've never had any experience publishing to Sonatype but I hear it's difficult so I'm not keen to go down that path just yet.

FWIW It's heartening to see that people are still using the plugins!

**Comment by davegurnell** [comment]
On a hunch, I've created an alternate ivy-style repo and pushed 0.8 there. @ivorwilliams @luismfonseca  Can you try this for me in your `plugins.sbt` and let me know if it works?

``` scala
resolvers += Resolver.url(s"bintray-untyped-ivy", new URL("https://dl.bintray.com/untyped/ivy/"))(Resolver.ivyStylePatterns)

addSbtPlugin(/* etc */)
```

**Comment by luismfonseca** [comment]
Thanks for keeping the project alive and helping us out :).

I've published to Sonatype before and there's an initial effort as there are things things you have to check/do before your first publish, but after that it's as easy as publishing to bintray.

I've tried your suggestion and it works:

```
[info] downloading https://dl.bintray.com/untyped/ivy/com.untyped/sbt-js/scala_2.10/sbt_0.13/0.8/jars/sbt-js.jar ...
[info]  [SUCCESSFUL ] com.untyped#sbt-js;0.8!sbt-js.jar (1746ms)
```

**Comment by davegurnell** [comment]
Ok great. Thanks for your patience and sorry for the problems.

I've updated the installation instructions in the README in 3a1f1fc. I'll delete the Untyped Maven Bintray repo (which is only being used for these plugins) and move everything to the Ivy repo.

I'll also look into wider long-term publishing. Sonatype, jCenter, and the SBT Community Plugins repo are all automatically picked up by SBT so I'll look into them in due course.

**Comment by ivorwilliams** [comment]
Works for me!  Thanks for the fast fix, @davegurnell.
